# syntax=docker/dockerfile:1

ARG RUST_VERSION=1.97.1
ARG APP_NAME=webauthn_backend
ARG ALPINE_VERSION=3.23
ARG PORT=8080

FROM rust:${RUST_VERSION}-alpine3.23 AS build
ARG APP_NAME
WORKDIR /app

RUN apk add --no-cache clang lld musl-dev pkgconfig openssl-dev openssl-libs-static

COPY . .

RUN --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
    SQLX_OFFLINE=true cargo build --locked --release && \
    cp ./target/release/${APP_NAME} /bin/server

FROM alpine:${ALPINE_VERSION} AS final

ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

RUN apk add --no-cache openssl

USER appuser

COPY --from=build /bin/server /bin/

EXPOSE 8080

CMD ["/bin/server"]
