# Cilium Helm Chart Configuration
gatewayAPI:
  enabled: true

kubeProxyReplacement: true

l2announcements:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
