apiVersion: v1
kind: ConfigMap
metadata:
  name: yubi-frontend-config
data:
  PORT: "3000"
  BACKEND_URL: "http://yubi-backend:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yubi-frontend
spec:
  selector:
    matchLabels:
      app: yubi-frontend
  template:
    metadata:
      labels:
        app: yubi-frontend
    spec:
      containers:
      - name: frontend
        image: localhost/yubi-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: yubi-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: yubi-frontend
spec:
  selector:
    app: yubi-frontend
  ports:
  - port: 3000
    targetPort: 3000
