apiVersion: batch/v1
kind: Job
metadata:
  name: yubi-migrations
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: localhost/yubi-migrations:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: yubi-pg-app
              key: uri
