apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: yubi-pg
spec:
  imageName: docker.io/library/postgres:18.4-trixie
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: yubi
      owner: yubi_migrator
      postInitApplicationSQL:
        - "CREATE ROLE yubi_app WITH LOGIN PASSWORD 'app_secret';"
        - "GRANT CONNECT ON DATABASE yubi TO yubi_app;"
        - "GRANT USAGE ON SCHEMA public TO yubi_app;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO yubi_app;"
        - "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO yubi_app;"
